### ISSUE TITLE
无法正常clone仓库

### ISSUE THREAD

**Issue by SilverLeaves** [program-in-chinese/team_website#18]
git version 2.19.1.windows.1
![default](https://user-images.githubusercontent.com/31165554/53058760-6c480c80-34ef-11e9-8e6d-8e11d5f919f8.png)

**Comment by SilverLeaves** [comment]
github destop 1.62

![default](https://user-images.githubusercontent.com/31165554/53058868-c8ab2c00-34ef-11e9-8557-72aeea6d6150.png)

**Comment by nobodxbodon** [comment]
大概是引号惹的祸. mac下是支持的. 再试试?

**Comment by nobodxbodon** [comment]
去掉了文件中的问号. 请再试?

**Comment by SilverLeaves** [comment]
![default](https://user-images.githubusercontent.com/31165554/53080140-fa91b200-3532-11e9-9614-73f0d1d23348.png)

**Comment by SilverLeaves** [comment]
可以了
