### ISSUE TITLE
请求：开一个新的基于vuepress的文档分支

### ISSUE THREAD

**Issue by SilverLeaves** [program-in-chinese/team_website#19]
http://mioss.pinza.ltd/cncode/index.html
Vuepress具有以下优点：

1. 搜索功能
2. 更优化的单页SPA应用的体验
3. 更好看的样式
4. 更多的功能

例如：http://mioss.pinza.ltd/xlsx/index.html

支持Vue组件

**Comment by SilverLeaves** [comment]
我尝试过，直接更改现有项目，但是太难了，
当前的markdown文档命名名称无法正常解析，内容格式不规范，导致无法直接迁移到vuepress

**Comment by nobodxbodon** [comment]
欢迎开新分支后提交PR.
另外, [之前](https://github.com/program-in-chinese/overview/issues/126#issuecomment-465422613)未得到回复. 如果短期内不打算在[lets_encrypte](https://github.com/program-in-chinese/lets_encrypte)项目中使用中文命名等等与中文编程相关的实践, 请先删除此fork.
